import "dotenv/config";
import { createCorsair } from "corsair";
import { pool } from "./db.js";

// Auto-generated by the Corsair control server.
// Use the /plugins page to add integrations — do not edit this file directly.

const PUBLIC_URL = process.env.PUBLIC_URL ?? "http://localhost:8080";

export const corsair = createCorsair({
  multiTenancy: true,
  database: pool,
  kek: process.env.CORSAIR_KEK || "",
  approval: {
    timeout: "1h",
    onTimeout: "deny",
    mode: "asynchronous",
    formatAsyncMessage: ({ token }: { token: string; id: string; plugin: string; endpoint: string; args: unknown }) =>
      `Approval required. Visit ${PUBLIC_URL}/approve/${token} to approve or deny, then retry.`,
  },
  plugins: [],
});
