import fs from "fs/promises";
import path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import { WORKSPACE_DEFAULTS_DIR, WORKSPACE_DIR } from "./config.js";

const exec = promisify(execFile);

// Files that are always synced from workspace-defaults on every boot.
// corsair.ts is excluded — it's auto-generated by codegen and must not be overwritten.
const ALWAYS_SYNC = ["src/index.ts", "src/db.ts"];

export async function initWorkspace(): Promise<void> {
  const srcDir = path.join(WORKSPACE_DIR, "src");

  try {
    await fs.access(srcDir);
    // Not first boot — just sync framework source files.
    for (const file of ALWAYS_SYNC) {
      await fs.copyFile(
        path.join(WORKSPACE_DEFAULTS_DIR, file),
        path.join(WORKSPACE_DIR, file),
      );
    }
    console.log("[workspace] Synced framework files");
    return;
  } catch {
    // Volume is empty — first boot
  }

  console.log("[workspace] First boot — copying defaults...");
  await fs.mkdir(WORKSPACE_DIR, { recursive: true });
  await exec("cp", ["-r", `${WORKSPACE_DEFAULTS_DIR}/.`, `${WORKSPACE_DIR}/`]);

  console.log("[workspace] Installing base packages...");
  await exec("npm", ["install"], { cwd: WORKSPACE_DIR, timeout: 180_000 });

  console.log("[workspace] Ready");
}
